version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - READWISE_API_TOKEN=${READWISE_API_TOKEN}
      - DEBUG=False

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
